#!/usr/bin/env perl 

use strict;
use warnings;

use FindBin;
BEGIN { do "$FindBin::Bin/env" or die $@ }

use CPAN;

for my $target ( @ARGV ) {
    my $module = CPAN::Shell->expand( Module => $target );
    $module->get;

    my $dir = CPAN::Shell->expand( Distribution => $module->cpan_file )->dir;
    chdir ( $dir );

    my $make = $CPAN::Config->{make};
    system( $^X, 'Makefile.PL', "--bootstrap=$target" ) && exit 1;
    system( $make, 'test' ) && exit 1;
    system( $make, 'install' ) && exit 1;
}
